HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_LIBRARY_ROOT         = evtbin

HD_LIBRARY_SRC_cxx      = BayesianBinner.cxx \
                          BinConfig.cxx \
                          ConstSnBinner.cxx \
                          CountCube.cxx \
                          CountMap.cxx \
                          DataProduct.cxx \
                          GlastGbmBinConfig.cxx \
                          GlastLatBinConfig.cxx \
                          Gti.cxx \
                          HealpixBinner.cxx \
                          HealpixMap.cxx \
                          Hist.cxx \
                          Hist1D.cxx \
                          Hist2D.cxx \
                          Hist3D.cxx \
                          LightCurve.cxx \
                          LinearBinner.cxx \
                          LogBinner.cxx \
                          MultiSpec.cxx \
                          OrderedBinner.cxx \
                          RecordBinFiller.cxx \
                          SingleSpec.cxx

HD_SUBDIRS              = gtbin gtbindef

HD_CXXFLAGS             = -fpermissive ${HD_STD_CXXFLAGS}

HD_INSTALL_LIBRARIES    = ${HD_LIBRARY_ROOT}

include ${HD_STD_MAKEFILE}
