HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_REFDATA      = caldb.indx

HD_REFDATA_SUBDIR       = fermi/caldb/CALDB/data/glast/lat

HD_SUBDIRS              = bcf

include ${HD_STD_MAKEFILE}
