HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = facilities

HD_INSTALL_HEADERS      = Adapter.h \
						  AssertDialogOverride.h \
                          Clock.h \
                          Commissioner.h \
                          Converter.h \
                          FIFO.h \
                          Observer.h \
                          ScheduledEvent.h \
                          Scheduler.h \
                          SimpleEvent.h \
                          Timestamp.h \
                          Util.h \
                          Utility.h \
                          XGetopt.h \
                          binarystream.h \
                          bitmanip.h \
                          bpkt_streams.h \
                          commonUtilities.h \
                          environmentCallback.h \
                          error.h \
                          filemap.h

include ${HD_STD_MAKEFILE}
