HD_COMPONENT_NAME	= glast

HD_COMPONENT_VERS	= 

HD_INC_SUBDIR		= timeSystem

HD_INSTALL_HEADERS	= \
                          AbsoluteTime.h \
                          BaryTimeComputer.h \
                          CalendarFormat.h \
			  Duration.h \
                          ElapsedTime.h \
                          EventTimeHandler.h \
                          Field.h \
			  GlastMetRep.h \
                          GlastTimeHandler.h \
                          IntFracPair.h \
                          IntFracUtility.h \
                          MjdFormat.h \
                          PulsarTestApp.h \
                          SourcePosition.h \
                          TimeConstant.h \
                          TimeCorrectorApp.h \
                          TimeFormat.h \
                          TimeInterval.h \
                          TimeSystem.h \
                          glastscorbit.h

include ${HD_STD_MAKEFILE}
