HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_XML_SUBDIR           = fermi/GRBobs

HD_TEST_XML             = GRBobs_grid_library.xml \
                          GRBobs_user_library.xml \
                          grb_position.txt \
                          l_b_coords.txt \
                          SWIFT_bursts.xml

include ${HD_STD_MAKEFILE}
