HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/pulsePhase/outref

HD_TEST_REFDATA         = psrdb_summary.txt \
                          testOrbitalPhaseApp_par1a.fits \
                          testOrbitalPhaseApp_par1b.fits \
                          testOrbitalPhaseApp_par1c.fits \
                          testOrbitalPhaseApp_par2.fits \
                          testOrbitalPhaseApp_par2.log \
                          testOrbitalPhaseApp_par3.fits \
                          testOrbitalPhaseApp_par3.log \
                          testOrbitalPhaseApp_par4.fits \
                          testOrbitalPhaseApp_par4.log \
                          testOrbitalPhaseApp_par5.fits \
                          testOrbitalPhaseApp_par5.log \
                          testOrbitalPhaseApp_par5.ref \
                          testOrbitalPhaseApp_par6.fits \
                          testOrbitalPhaseApp_par6.log \
                          testOrbitalPhaseApp_par6.ref \
                          testOrbitalPhaseApp_par7.fits \
                          testOrbitalPhaseApp_par7.log \
                          testOrbitalPhaseApp_par7.ref \
                          testOrbitalPhaseApp_par8.fits \
                          testOrbitalPhaseApp_par9.fits \
                          testOrbitalPhaseApp_par10.fits \
                          testPulsePhaseApp_par10.fits \
                          testPulsePhaseApp_par10.log \
                          testPulsePhaseApp_par11.fits \
                          testPulsePhaseApp_par11.log \
                          testPulsePhaseApp_par11.ref \
                          testPulsePhaseApp_par12.fits \
                          testPulsePhaseApp_par12.log \
                          testPulsePhaseApp_par12.ref \
                          testPulsePhaseApp_par13.fits \
                          testPulsePhaseApp_par13.log \
                          testPulsePhaseApp_par13.ref \
                          testPulsePhaseApp_par1a.fits \
                          testPulsePhaseApp_par1b.fits \
                          testPulsePhaseApp_par1c.fits \
                          testPulsePhaseApp_par2a.fits \
                          testPulsePhaseApp_par2b.fits \
                          testPulsePhaseApp_par2c.fits \
                          testPulsePhaseApp_par2c.log \
                          testPulsePhaseApp_par3a.fits \
                          testPulsePhaseApp_par3b.fits \
                          testPulsePhaseApp_par3c.fits \
                          testPulsePhaseApp_par4a.fits \
                          testPulsePhaseApp_par4b.fits \
                          testPulsePhaseApp_par4c.fits \
                          testPulsePhaseApp_par4d.fits \
                          testPulsePhaseApp_par5.fits \
                          testPulsePhaseApp_par5.log \
                          testPulsePhaseApp_par6.fits \
                          testPulsePhaseApp_par6.log \
                          testPulsePhaseApp_par7.fits \
                          testPulsePhaseApp_par7.log \
                          testPulsePhaseApp_par8.fits \
                          testPulsePhaseApp_par8.log \
                          testPulsePhaseApp_par9.fits \
                          testPulsePhaseApp_par9.log

include ${HD_STD_MAKEFILE}
