HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = latResponse

HD_INSTALL_HEADERS      = Bilinear.h FitsTable.h IrfLoader.h ParTables.h

include ${HD_STD_MAKEFILE}
