HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/eblAtten

HD_TEST_REFDATA         =  opdep_fiducial_Gilmore2012.dat \
						   opdep_fixed_Gilmore2012.dat \
						   readme_Gilmore2012.txt

include ${HD_STD_MAKEFILE}
