HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/burstFit

HD_TEST_REFDATA         = binData1039.fits \
                          binData1406.fits \
                          binData2193.fits \
                          binData2197.fits \
                          binData2387.fits \
                          binData2665.fits \
                          binData2711.fits \
                          binData2863.fits \
                          binData3256.fits \
                          binData3257.fits \
                          binData5387.fits \
                          binData5415.fits \
                          binData6147.fits \
                          binData6414.fits \
                          binData6504.fits \
                          binData764.fits \
                          ft1tiny.fits \
                          n0_p05.lc

include ${HD_STD_MAKEFILE}
