HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/pulsePhase

HD_TEST_REFDATA         = D1.fits \
                          master_pulsardb_v2.fits \
                          my_pulsar_events_2gti.fits \
                          my_pulsar_events_v3.fits \
                          my_pulsar_events_v3r1.fits \
                          my_pulsar_spacecraft_data_v3r1.fits \
                          psrdb_binary.txt \
                          psrdb_glitch.txt \
                          psrdb_remark.txt \
                          psrdb_spin1.txt \
                          psrdb_spin2.txt \
                          psrdb_spin3.txt \
                          psrdb_spin4.txt \
                          psrdb_spin5.txt \
                          psrdb_spin6.txt \
                          testevdata_1day_2gti.fits \
                          testevdata_1day_unordered.fits \
                          testevdata_1year.fits \
                          testpsrdb_ephcomp.fits \
                          testpsrdb_orbital_bt.txt \
                          testpsrdb_orbital_dd.txt \
                          testpsrdb_orbital_ell1.txt \
                          testpsrdb_orbital_mss.txt \
                          testpsrdb_spin_freq.txt \
                          testpsrdb_spin_hp.txt \
                          testpsrdb_spin_per.txt \
                          testscdata_1day.fits \
                          testscdata_1year.fits

include ${HD_STD_MAKEFILE}
