HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/genericSources

HD_TEST_REFDATA         = 3c279Template.dat \
                          CrabTemplate.dat \
                          GemingaTemplate.dat \
                          dm120gev.dat \
                          energy_dist.dat \
                          fitsSpectrum.fits \
                          isotropic_iem_v02.txt \
                          pks1622-297_Template.dat \
                          radial_dist.dat \
                          sourcePop.dat \
                          testTemplate.dat \
                          test_image.fits

include ${HD_STD_MAKEFILE}
