HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/timeSystem

HD_TEST_REFDATA         = bogusls.fits \
                          my_pulsar_events_bary_v3.fits \
                          my_pulsar_events_bary_v3r1.fits \
                          my_pulsar_events_geo_v3.fits \
                          my_pulsar_events_geo_v3r1.fits \
                          my_pulsar_events_v3.fits \
                          my_pulsar_events_v3r1.fits \
                          my_pulsar_events_v4.fits \
                          my_pulsar_spacecraft_data_v3.fits \
                          my_pulsar_spacecraft_data_v3r1.fits \
                          my_pulsar_spacecraft_data_v4.fits \
                          testevdata_1day.fits \
                          testevdata_1day_bary.fits \
                          testevdata_1day_fermi.fits \
                          testevdata_1day_geo.fits \
                          testevdata_1day_unordered.fits \
                          testevdata_1day_unordered_bary.fits \
                          testevdata_1day_unordered_geo.fits \
                          testls.fits \
                          testscdata_1day.fits \
                          testscdata_1day_fermi.fits \
                          testscfile_3rd.fits \
                          testscfile_lam.fits \
                          testscfile_one.fits \
                          testscfile_std.fits

include ${HD_STD_MAKEFILE}
