.TH "AtEulerAng" 3 "Mon May 5 2014" "gtorbsim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AtEulerAng \- 
.PP
Structure that contains 3 Euler angles\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <orbitSimStruct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBphi\fP"
.br
.RI "\fIFirst Euler Angle (radian) \fP"
.ti -1c
.RI "double \fBtheta\fP"
.br
.RI "\fISecond Euler Angle (radian) \fP"
.ti -1c
.RI "double \fBpsi\fP"
.br
.RI "\fIThird Euler Angle (radian) \fP"
.in -1c
.SH "Detailed Description"
.PP 
Structure that contains 3 Euler angles\&. 

Euler angle notation of rotation\&. (usually z-y-z)
.PP
\fBAuthor:\fP
.RS 4
Giuseppe Romeo 
.RE
.PP
\fBDate:\fP
.RS 4
Created: Nov 15, 2005 
.PP
Last Modified: Feb 08, 2006 
.RE
.PP

.PP
Definition at line 209 of file orbitSimStruct\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double \fBAtEulerAng::phi\fP"
.PP
First Euler Angle (radian) 
.PP
Definition at line 211 of file orbitSimStruct\&.h\&.
.SS "double \fBAtEulerAng::psi\fP"
.PP
Third Euler Angle (radian) 
.PP
Definition at line 215 of file orbitSimStruct\&.h\&.
.SS "double \fBAtEulerAng::theta\fP"
.PP
Second Euler Angle (radian) 
.PP
Definition at line 213 of file orbitSimStruct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for gtorbsim from the source code\&.
