.TH "AtPolarVect" 3 "Mon May 5 2014" "gtorbsim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AtPolarVect \- 
.PP
Three-dimensional Vector in Polar coordinate\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <orbitSimStruct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBr\fP"
.br
.RI "\fIradial component \fP"
.ti -1c
.RI "double \fBlon\fP"
.br
.RI "\fIlongitude or R\&.A\&. (radian) \fP"
.ti -1c
.RI "double \fBlat\fP"
.br
.RI "\fIlatitude or declination (radian) \fP"
.in -1c
.SH "Detailed Description"
.PP 
Three-dimensional Vector in Polar coordinate\&. 

\fBAuthor:\fP
.RS 4
Giuseppe Romeo 
.RE
.PP
\fBDate:\fP
.RS 4
Created: Nov 15, 2005 
.PP
Last Modified: Feb 08, 2006 
.RE
.PP

.PP
Definition at line 229 of file orbitSimStruct\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double \fBAtPolarVect::lat\fP"
.PP
latitude or declination (radian) 
.PP
Definition at line 235 of file orbitSimStruct\&.h\&.
.SS "double \fBAtPolarVect::lon\fP"
.PP
longitude or R\&.A\&. (radian) 
.PP
Definition at line 233 of file orbitSimStruct\&.h\&.
.SS "double \fBAtPolarVect::r\fP"
.PP
radial component 
.PP
Definition at line 231 of file orbitSimStruct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for gtorbsim from the source code\&.
