.TH "AtTime" 3 "Mon May 5 2014" "gtorbsim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AtTime \- 
.PP
Structure that contains time parameters\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <orbitSimStruct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fByr\fP"
.br
.RI "\fIyear \fP"
.ti -1c
.RI "int \fBmo\fP"
.br
.RI "\fImonth \fP"
.ti -1c
.RI "int \fBdy\fP"
.br
.RI "\fIday \fP"
.ti -1c
.RI "int \fBhr\fP"
.br
.RI "\fIhour \fP"
.ti -1c
.RI "int \fBmn\fP"
.br
.RI "\fIminute \fP"
.ti -1c
.RI "int \fBsc\fP"
.br
.RI "\fIsec \fP"
.ti -1c
.RI "float \fBms\fP"
.br
.RI "\fImillisec \fP"
.in -1c
.SH "Detailed Description"
.PP 
Structure that contains time parameters\&. 

This structure contains all time parameters
.PP
\fBAuthor:\fP
.RS 4
Giuseppe Romeo 
.RE
.PP
\fBDate:\fP
.RS 4
Created: Nov 15, 2005 
.PP
Last Modified: Feb 08, 2006 
.RE
.PP

.PP
Definition at line 111 of file orbitSimStruct\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int \fBAtTime::dy\fP"
.PP
day 
.PP
Definition at line 117 of file orbitSimStruct\&.h\&.
.SS "int \fBAtTime::hr\fP"
.PP
hour 
.PP
Definition at line 119 of file orbitSimStruct\&.h\&.
.SS "int \fBAtTime::mn\fP"
.PP
minute 
.PP
Definition at line 121 of file orbitSimStruct\&.h\&.
.SS "int \fBAtTime::mo\fP"
.PP
month 
.PP
Definition at line 115 of file orbitSimStruct\&.h\&.
.SS "float \fBAtTime::ms\fP"
.PP
millisec 
.PP
Definition at line 125 of file orbitSimStruct\&.h\&.
.SS "int \fBAtTime::sc\fP"
.PP
sec 
.PP
Definition at line 123 of file orbitSimStruct\&.h\&.
.SS "int \fBAtTime::yr\fP"
.PP
year 
.PP
Definition at line 113 of file orbitSimStruct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for gtorbsim from the source code\&.
