.TH "orbitSim/orbitSim/DynamicStruct.h" 3 "Mon May 5 2014" "gtorbsim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
orbitSim/orbitSim/DynamicStruct.h \- 
.PP
This file contains all dynamically allocated structures definition used by the orbit Simulator\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBEphemData\fP"
.br
.RI "\fIStructure that contains all ephemeredis information\&. \fP"
.ti -1c
.RI "struct \fBAttitude\fP"
.br
.RI "\fIStructure that contains all attitude information\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This file contains all dynamically allocated structures definition used by the orbit Simulator\&. 

\fBAuthor:\fP
.RS 4
Giuseppe Romeo 
.RE
.PP
\fBDate:\fP
.RS 4
Created: Nov 15, 2005
.RE
.PP
\fBHeader:\fP
.RS 4
/nfs/slac/g/glast/ground/cvs/ScienceTools-scons/orbitSim/orbitSim/DynamicStruct\&.h,v 1\&.3 2008/09/25 17:20:28 vernaleo Exp 
.RE
.PP

.PP
Definition in file \fBDynamicStruct\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for gtorbsim from the source code\&.
