.TH "orbitSim/orbitSim/GLAST_slew_estimate.h" 3 "Mon May 5 2014" "gtorbsim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
orbitSim/orbitSim/GLAST_slew_estimate.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBGLAST_slew_estimate\fP (double ra_s, double dec_s, double ra_i, double dec_i, double ra_f, double dec_f)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double \fBGLAST_slew_estimate\fP (doublera_s, doubledec_s, doublera_i, doubledec_i, doublera_f, doubledec_f)"
.PP
Definition at line 329 of file GLAST_slew_estimate\&.cxx\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for gtorbsim from the source code\&.
