.TH "vector" 3 "Mon May 5 2014" "gtorbsim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vector \- 
.PP
Structure that contains 3D vector plus its magnitude\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <orbitSimStruct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBv\fP [4]"
.br
.RI "\fI3-dimensional vector, the fourth element contains the magnitude \fP"
.in -1c
.SH "Detailed Description"
.PP 
Structure that contains 3D vector plus its magnitude\&. 

\fBAuthor:\fP
.RS 4
Giuseppe Romeo 
.RE
.PP
\fBDate:\fP
.RS 4
Created: Nov 15, 2005 
.PP
Last Modified: Mar 14, 2007 
.RE
.PP

.PP
Definition at line 188 of file orbitSimStruct\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double \fBvector::v\fP[4]"
.PP
3-dimensional vector, the fourth element contains the magnitude 
.PP
Definition at line 190 of file orbitSimStruct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for gtorbsim from the source code\&.
