HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_XML_SUBDIR           = fermi/xmlBase

HD_TEST_XML             = myIFile.xml \
                          mySchemaIFile.xml \
                          simpleDoc.xml \
                          simple.dtd \
                          simpleExternal.xml \
                          test-dtd.xml \
                          test.xml

include ${HD_STD_MAKEFILE}
