HD_COMPONENT_NAME	= glast

HD_COMPONENT_VERS	= 

HD_LIBRARY_ROOT         = pulsePhase

HD_LIBRARY_SRC_cxx      = OrbitalPhaseApp.cxx PulsePhaseApp.cxx

HD_CXXFLAGS		= ${HD_STD_CXXFLAGS}

HD_INSTALL_LIBRARIES	= ${HD_LIBRARY_ROOT}

HD_SUBDIRS              = gtophase gtpphase

HD_TEST_SUBDIRS		= test

include ${HD_STD_MAKEFILE}
