HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/observationSim

HD_TEST_REFDATA         = 3c279Template.dat \
                          CrabTemplate.dat \
                          GemingaTemplate.dat \
                          pks1622-297_Template.dat \
                          pointing_history.txt \
                          source_names.dat \
                          xml_files.dat

include ${HD_STD_MAKEFILE}
