HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_SUBDIRS              = irfLoader src pfiles

HD_TEST_SUBDIRS         = src/test

HD_TEST_SUBDIRS         = src/test

include ${HD_STD_MAKEFILE}
