HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_SUBDIRS              = irfInterface \
                          irfUtil \
                          caldb_release \
                          dc1aResponse \
                          latResponse \
                          testResponse \
                          irfLoader \
                          pyIrfLoader \
#                          rootIrfLoader

HD_TEST_SUBDIRS         = irfInterface \
                          dc1aResponse \
                          latResponse \
                          testResponse \
                          irfLoader \
                          irfUtil

include ${HD_STD_MAKEFILE}
