HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_LIBRARY_ROOT         = latResponse

HD_LIBRARY_SRC_cxx      = Aeff.cxx \
						  AeffEpochDep.cxx \
                          Bilinear.cxx \
                          Edisp.cxx \
                          Edisp2.cxx \
                          Edisp3.cxx \
                          EdispInterpolator.cxx \
                          EdispEpochDep.cxx \
                          EfficiencyFactor.cxx \
                          EfficiencyFactorEpochDep.cxx \
                          EpochDep.cxx \
                          FitsTable.cxx \
                          IrfLoader.cxx \
                          ParTables.cxx \
                          Psf.cxx \
                          Psf2.cxx \
                          Psf3.cxx \
                          PsfBase.cxx \
                          PsfIntegralCache.cxx \
                          PsfEpochDep.cxx 

HD_CXXFLAGS             = ${HD_STD_CXXFLAGS}

HD_INSTALL_LIBRARIES    = ${HD_LIBRARY_ROOT}

HD_SUBDIRS              = combine_irfs

include ${HD_STD_MAKEFILE}
