HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_TEST_TASKS           = test_healpix

HD_TEST_CXXTASK         = ${HD_TEST_TASKS}

HD_TEST_CXXTASK_SRC_cxx	= test_healpix.cxx

HD_CXXFLAGS             = ${HD_STD_CXXFLAGS} -fpermissive -I../..

HD_CXXLIBS              = ${HD_LFLAGS} \
                          ${GT_HEALPIX_LIBS} \
                          ${GT_STD_CXXLIBS}

include ${HD_STD_MAKEFILE}
