HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = tip

HD_INSTALL_HEADERS      = Extension.h \
                          FileSummary.h \
                          Header.h \
                          IColumn.h \
                          IFileSvc.h \
                          Image.h \
                          Iterator.h \
                          KeyRecord.h \
                          LinearInterp.h \
                          ScalarAdaptor.h \
                          Table.h \
                          TipException.h \
                          TipFile.h \
                          VectorAdaptor.h \
                          tip_types.h

include ${HD_STD_MAKEFILE}
