HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_PYTHON_LIBS  = cleanXml.py \
                          GtApp.py \
                          gt_apps.py \
                          makeSrcList.py \
                          menu.py \
                          pfilesPath.py \
                          pil.py \
                          readXml.py \
                          source_analysis.py \
                          xmlSrcLib.py

HD_SUBDIRS              = tests

include ${HD_STD_MAKEFILE}
