HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_XML          = 3EG_catalog.xml \
                          obsSim_source_library.xml \
                          time_source.xml \
                          xmlFiles.dat

HD_XML_SUBDIR           = fermi/observationSim

HD_TEST_XML             = test_sources_v2.xml \
                          test_sources.xml \
                          time_source.xml 3EG_catalog_20-1e6MeV.xml

include ${HD_STD_MAKEFILE}
