HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = SolarSystemTools

HD_INSTALL_HEADERS      = BinnedExposureSun.h \
						  CosineBinner2D.h \
						  ExposureCubeSun.h \
						  ExposureSun.h \
						  FitsSolarProfile.h \
						  HealpixExposureSun.h \
						  LikeExposureSun.h \
						  Observation.h \
						  SolarProfile.h \
						  SolarTemplate.h

include ${HD_STD_MAKEFILE}