HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_LIBRARY_ROOT         = optimizers

HD_LIBRARY_SRC_c        = dgaus8.c \
                          dpptri-blas.c \
                          dpptri.c \
                          drmnfb_routines.c \
                          drmngb_routines.c \
                          intrac.c \
                          lbfgs_routines.c \
                          minuit_routines.c

HD_LIBRARY_SRC_cxx      = AbsEdge.cxx \
                          Amoeba.cxx \
                          BrokenPowerLaw.cxx \
                          ChiSq.cxx \
                          CompositeFunction.cxx \
                          Dom.cxx \
                          Drmnfb.cxx \
                          Drmngb.cxx \
                          Function.cxx \
                          FunctionFactory.cxx \
                          FunctionTest.cxx \
                          Gaussian.cxx \
                          Lbfgs.cxx \
                          Mcmc.cxx \
                          Minuit.cxx \
                          ModNewton.cxx \
                          MyFun.cxx \
                          NewMinuit.cxx \
                          OptPP.cxx \
                          Optimizer.cxx \
                          OptimizerFactory.cxx \
                          Parameter.cxx \
                          Powell.cxx \
                          PowerLaw.cxx \
                          ProductFunction.cxx \
                          Rosen.cxx \
                          RosenBounded.cxx \
                          RosenND.cxx \
                          StMnMinos.cxx \
                          SumFunction.cxx \
                          Util.cxx

HD_CFLAGS               = ${HD_STD_CFLAGS}

HD_CXXFLAGS             = ${HD_STD_CXXFLAGS}

HD_INSTALL_LIBRARIES	= ${HD_LIBRARY_ROOT}

include ${HD_STD_MAKEFILE}
