HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_LIBRARY_ROOT         = pyExposure

HD_LIBRARY_SRC_cxx      = Exposure.cxx

HD_SUBDIRS              = gtexposure

HD_CXXFLAGS             = ${HD_STD_CXXFLAGS} -fpermissive

HD_INSTALL_LIBRARIES    = ${HD_LIBRARY_ROOT}

include ${HD_STD_MAKEFILE}
