HD_COMPONENT_NAME	= glast

HD_COMPONENT_VERS	= 

HD_REFDATA_SUBDIR       = fermi/evtbin/outref

HD_TEST_REFDATA         = LC1.lc \
			  PHA2.pha \
                          CM2.fits \
                          GBMLC1.lc \
                          GBMPHA1.pha \
                          PHA1.pha \
                          merged_spectrum.pha \
                          separate_spectrum.pha \
                          test.ccube

include ${HD_STD_MAKEFILE}
