HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = dataSubselector

HD_INSTALL_HEADERS      = BitMaskCut.h \
                          CutBase.h \
                          Cuts.h \
                          Gti.h \
                          GtiCut.h \
                          RangeCut.h \
                          SkyConeCut.h \
                          VersionCut.h

include ${HD_STD_MAKEFILE}
