HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/GRBtemplate/outref

HD_TEST_REFDATA         = BGO_GRBTMP_010204722.lc \
                          BGO_GRBTMP_010311444.lc \
                          BGO_GRBTMP_010415166.lc \
                          BGO_GRBTMP_010519888.lc \
                          GRBTMP_010204722.DEF \
                          GRBTMP_010311444.DEF \
                          GRBTMP_010415166.DEF \
                          GRBTMP_010519888.DEF \
                          NaI_GRBTMP_010204722.lc \
                          NaI_GRBTMP_010311444.lc \
                          NaI_GRBTMP_010415166.lc \
                          NaI_GRBTMP_010519888.lc \
                          test_GRB.out

include ${HD_STD_MAKEFILE}
