HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       = 

HD_INSTALL_XML          = FunctionModels.dtd

HD_XML_SUBDIR           = fermi/optimizers

HD_TEST_XML             = BadModel.xml FunctionModels.xml

include ${HD_STD_MAKEFILE}
