HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_REFDATA      = irf_index.fits valid_evclass_selections.txt valid_evtype_selections.txt

HD_REFDATA_SUBDIR       = fermi/caldb/CALDB/data/glast/lat/bcf

HD_SUBDIRS              = ea edisp psf

include ${HD_STD_MAKEFILE}
