HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_REFDATA      = alias_config.fits caldb.config

HD_REFDATA_SUBDIR       = fermi/caldb/CALDB/software/tools

include ${HD_STD_MAKEFILE}
