HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_SUBDIRS              = periodSearch src pfiles data

HD_TEST_SUBDIRS         = src/test pfiles data data/outref

include ${HD_STD_MAKEFILE}
