HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_SUBDIRS              = pyBurstAnalysisGUI src python

HD_INSTALL_REFDATA	= -r data/*

HD_REFDATA_SUBDIR	=	fermi/pyBurstAnalysisGUI

include ${HD_STD_MAKEFILE}
