HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_LIBRARY_ROOT         = burstFit

HD_LIBRARY_SRC_cxx      = BurstModel.cxx NegativeStat.cxx

HD_CXXFLAGS             = ${HD_STD_CXXFLAGS}

HD_INSTALL_LIBRARIES    = ${HD_LIBRARY_ROOT}

HD_SUBDIRS              = gtburstfit

include ${HD_STD_MAKEFILE}
