HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = Likelihood

HD_INSTALL_HEADERS      = Accumulator.h \
                          AppHelpers.h \
                          BandFunction.h \
                          BinnedExposure.h \
                          BinnedLikelihood.h \
                          BinnedLikelihood2.h \
                          BinnedHealpixExposure.h \
                          BrokenPowerLaw2.h \
                          BrokenPowerLaw3.h \
                          BrokenPowerLawExpCutoff.h \
                          Composite2.h \
                          CompositeLikelihood.h \
                          Convolve.h \
                          CountsMap.h \
                          CountsSpectra.h \
                          DMFitFunction.h \
                          DiffRespIntegrand.h \
                          DiffRespIntegrand2.h \
                          DiffRespNames.h \
                          DiffuseSource.h \
                          Drm.h \
                          EblAtten.h \
                          EnergyBand.h \
                          EquinoxRotation.h \
                          Event.h \
                          EventContainer.h \
                          EventSourceCache.h \
                          Exception.h \
                          ExpCutoff.h \
                          ExpCutoffSEDPeak.h \
                          ExposureCube.h \
                          ExposureMap.h \
                          FileFunction.h \
                          FluxBuilder.h \
                          HistND.h \
                          LikeExposure.h \
                          LogGaussian.h \
                          LogLike.h \
                          LogNormal.h \
                          LogNormalLog.h \
                          LogParabola.h \
                          MapBase.h \
                          MapCubeFunction2.h \
                          MeanPsf.h \
                          MultipleBrokenPowerLaw.h \
                          ModelMap.h \
                          Npred.h \
                          Observation.h \
                          OneSourceFunc.h \
                          OptEM.h \
                          PiecewisePowerLaw.h \
                          Pixel.h \
                          PointSource.h \
                          PowerLaw2.h \
                          PowerLawSuperExpCutoff.h \
                          RadialProfile.h \
                          ResponseFunctions.h \
                          RoiCuts.h \
                          ScData.h \
                          ScaleFactor.h \
                          SkyDirArg.h \
                          SkyDirFunction.h \
                          SmoothBrokenPowerLaw.h \
                          SmoothDoubleBrokenPowerLaw.h \
                          Source.h \
                          SourceFactory.h \
                          SourceMap.h \
                          SourceModel.h \
                          SourceModelBuilder.h \
                          SpatialMap.h \
                          SrcArg.h \
                          SummedLikelihood.h \
                          TiedParameter.h \
                          TrapQuad.h \
                          Util.h \
                          WcsMap.h \
                          WcsMap2.h \
                          WcsMapLibrary.h \
                          XmlBuilder.h \
                          XmlParser.h

include ${HD_STD_MAKEFILE}
