HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_LIBRARY_ROOT         = embed_python

HD_LIBRARY_SRC_cxx      = Module.cxx

HD_CXXFLAGS             = ${HD_STD_CXXFLAGS} ${PYTHON_INC}

HD_INSTALL_LIBRARIES    = ${HD_LIBRARY_ROOT}

include ${HD_STD_MAKEFILE}
