HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = celestialSources

HD_INSTALL_HEADERS      = ConstParMap.h \
						  SpectrumFactoryLoader.h \
						  TRandom4.h

include ${HD_STD_MAKEFILE}
