HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_REFDATA      = period-search-out.tpl

HD_REFDATA_SUBDIR       = fermi/periodSearch

HD_TEST_REFDATA         = ft1tiny.fits \
                          groD4-dc2v3.fits \
                          groD4-dc2v4.fits \
                          master_pulsardb_v2.fits \
                          my_pulsar_events_2gti.fits \
                          my_pulsar_events_phase_v3r1.fits \
                          my_pulsar_events_phase_v3r2.fits \
                          my_pulsar_events_v3.fits \
                          my_pulsar_events_v3r1.fits \
                          my_pulsar_spacecraft_data_bogus.fits \
                          my_pulsar_spacecraft_data_v3r1.fits \
                          periodicity-test-out.tpl \
                          psrdb_binary.txt \
                          psrdb_remark.txt \
                          psrdb_spin.txt \
                          testscdata_bogus.fits \
                          testevdata_1day_unordered_phase.fits \
                          psrdb_glitch.txt \
                          testscdata_1day.fits \
                          testpsrdb_ephcomp.fits \
                          testevdata_1day_unordered.fits \
                          testevdata_1day_2gti.fits \
                          testevdata_1day_psearch.fits \
                          step-01.fits

include ${HD_STD_MAKEFILE}
