HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = evtbin

HD_INSTALL_HEADERS      = BayesianBinner.h \
                          BinConfig.h \
                          Binner.h \
                          ConstSnBinner.h \
                          CountCube.h \
                          CountMap.h \
                          DataProduct.h \
                          Gti.h \
                          HealpixBinner.h \
                          HealpixMap.h \
                          Hist.h \
                          Hist1D.h \
                          Hist2D.h \
                          Hist3D.h \
                          LightCurve.h \
                          LinearBinner.h \
                          LogBinner.h \
                          MultiSpec.h \
                          OrderedBinner.h \
                          RecordBinFiller.h \
                          SingleSpec.h

include ${HD_STD_MAKEFILE}
