HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_XML_SUBDIR           = fermi/evtUtils

HD_TEST_XML             = EvtClassDefs_P7V6.xml \
						  EvtClassDefs_P7REP.xml \
                          EvtClassDefs_Test.xml \
                          EvtClassDefs_P7V3.xml \
                          EvtClassDefs_P8.xml \
                          EvtClassDefs_P8R2.xml \
                          EvtClassDefs_P8V1.xml

include ${HD_STD_MAKEFILE}
