HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/periodSearch/outref

HD_TEST_REFDATA         = artificial-chi-sq.fits \
                          artificial-fourier.fits \
                          artificial-h.fits \
                          artificial-rayleigh.fits \
                          artificial-z2n.fits \
                          psrb0540-chi-sq.fits \
                          psrb0540-fourier.fits \
                          psrb0540-h.fits \
                          psrb0540-pdot-chi-sq.fits \
                          psrb0540-pdot-fourier.fits \
                          psrb0540-pdot-h.fits \
                          psrb0540-pdot-rayleigh.fits \
                          psrb0540-pdot-z2n.fits \
                          psrb0540-rayleigh.fits \
                          psrb0540-z2n.fits \
                          psrdb_summary.txt \
                          testPeriodicityTestApp_par1.fits \
                          testPeriodicityTestApp_par1.log \
                          testPeriodSearchApp_par1.fits \
                          testPeriodSearchApp_par1.log \
                          testPeriodSearchApp_par2.log \
                          testPeriodSearchApp_par2.ref \
                          testPeriodSearchApp_par3.log \
                          testPeriodSearchApp_par3.ref \
                          testPeriodSearchApp_par4.log \
                          testPeriodSearchApp_par4.ref \
                          testPowerSpectrumApp_par1.fits \
                          testPowerSpectrumApp_par1.log \
                          testPowerSpectrumApp_par2.log \
                          testPowerSpectrumApp_par2.ref \
                          testPowerSpectrumApp_par3.log \
                          testPowerSpectrumApp_par3.ref \
                          testPowerSpectrumApp_par4.log \
                          testPowerSpectrumApp_par4.ref

include ${HD_STD_MAKEFILE}
