HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_REFDATA      = LivetimeCubeSunTemplate \
						  lunar_profile_v2r0.fits \
						  solar_profile_v2r0.fits

HD_REFDATA_SUBDIR       = fermi/SolarSystemTools

include ${HD_STD_MAKEFILE}
