HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = optimizers

HD_INSTALL_HEADERS      = Amoeba.h \
                          Arg.h \
                          ChiSq.h \
                          CompositeFunction.h \
                          dArg.h \
                          Dom.h \
                          Drmnfb.h \
                          Drmngb.h \
                          Exception.h \
                          f2c_types.h \
                          Function.h \
                          FunctionFactory.h \
                          FunctionTest.h \
                          Functor.h \
                          Gaussian.h \
                          Lbfgs.h \
                          Mcmc.h \
                          Minuit.h \
                          NewMinuit.h \
                          Optimizer.h \
                          OptimizerFactory.h \
                          OptPP.h \
                          OutOfBounds.h \
                          Parameter.h \
                          ParameterNotFound.h \
                          Powell.h \
                          ProductFunction.h \
                          Statistic.h \
                          SumFunction.h \
                          Util.h

include ${HD_STD_MAKEFILE}
