HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = GRBobs

HD_INSTALL_HEADERS      = GRBobsConstants.h \
                          GRBobsengine.h \
                          GRBobsmanager.h \
                          GRBobsPulse.h \
                          GRBobsSim.h \
                          SpectralComponent.h

include ${HD_STD_MAKEFILE}
