HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = st_app

HD_INSTALL_HEADERS      = AppParGroup.h \
                          StAppFactory.h \
                          StAppGui.h \
                          StApp.h \
                          StGui.h

include ${HD_STD_MAKEFILE}
