HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_REFDATA      = EvtClassDefs_Test.xml \
                          LLEvariables \
                          ft1.tpl \
                          ft1_p7.tpl \
                          ft2.tpl \
                          lle.tpl \
                          xml_test_merit.root

HD_REFDATA_SUBDIR       = fermi/fitsGen

include ${HD_STD_MAKEFILE}
