HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_PYTHON_LIBS = DC2_Classifier.py \
                         EventClassifier.py \
                         Ft1Validator.py \
                         Pass4_Classifier.py \
                         Pass5_Classifier.py \
                         Pass5_Classifier_old.py \
                         Pass6_kluge_Classifier.py

include ${HD_STD_MAKEFILE}
