HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_PYTHON_LIBS  = BayesianBlocks_python.py \
                          bb_analysis.py \
                          create_lc_file.py \
                          FitsNTuple.py \
                          test_BB_speed.py \
                          test_BB.py

include ${HD_STD_MAKEFILE}
