HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_SHELL_SCRIPTS = pypsf

HD_INSTALL_PYTHON_LIBS  = GtobspsfWidget.py \
                          GtpsfWidget.py \
                          HelpWindow.py \
                          PSFMath.py \
                          Parfile.py \
                          PyPSF.py

HD_INSTALL_HELP         = PyPSF.txt

include ${HD_STD_MAKEFILE}
