HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_LIBRARY_ROOT         = fitsGen

HD_LIBRARY_SRC_cxx      = EventClassifier.cxx \
                          Ft1File.cxx \
                          Ft2File.cxx \
                          FtFileBase.cxx \
                          MeritFile.cxx \
                          MeritFile2.cxx \
                          XmlEventClassifier.cxx

HD_CXXFLAGS             = ${HD_STD_CXXFLAGS} ${PYTHON_INC}

HD_INSTALL_LIBRARIES    = ${HD_LIBRARY_ROOT}

include ${HD_STD_MAKEFILE}
