HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_LIBRARY_ROOT         = GRBobs

HD_LIBRARY_SRC_cxx      = GRBobsConstants.cxx \
                          GRBobsengine.cxx \
                          GRBobsmanager.cxx \
                          GRBobsPulse.cxx \
                          GRBobsSim.cxx \
                          SpectralComponet.cxx

HD_CXXFLAGS             = ${HD_STD_CXXFLAGS}

HD_INSTALL_LIBRARIES    = ${HD_LIBRARY_ROOT}

include ${HD_STD_MAKEFILE}
