HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_LIBRARY_ROOT         = irfLoader

HD_LIBRARY_SRC_cxx      = Loader.cxx Registrar.cxx

HD_CXXFLAGS             = ${HD_STD_CXXFLAGS}

HD_INSTALL_LIBRARIES    = ${HD_LIBRARY_ROOT}

HD_SUBDIRS              = gtirfs

include ${HD_STD_MAKEFILE}
