HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/test-scripts/outref

HD_TEST_REFDATA         = _3c84_ExpCube.fits \
                          _3c84_sim_events_0000.fits \
                          counts_spectra.fits \
                          _3c84_ExpMap.fits \
                          _3c84_sim_ph02.fits \
                          _3c84_sim_cmap.fits \
                          _3c84_sim_srcIds.txt \
                          results.dat \
                          ST-gtephem.log \
                          testPeriodSearchApp_par1.fits \
                          testPowerSpectrumApp_par1.fits \
                          testOrbitalPhaseApp_par1.fits \
                          testPulsarDbApp_par2.fits \
                          testPeriodicityTestApp_par1.fits \
                          testPulsePhaseApp_par1.fits \
                          testTimeCorrectorApp_par1.fits \
                          3C84-P7REP-photons-outref.fits \
                          3C84-photons-outref.fits \
                          3C84-cmap-outref.fits \
                          3C84-expcube-outref.fits \
                          3C84-expmap-outref.fits \
                          3C84-results-outref.dat \
                          3C84-counts_spectra-outref.fits \
                          gtbary-out.fits \
                          gtpulsardb-out.fits \
                          gtpphase-out.fits \
                          gtophase-out.fits \
                          gtpsearch-out.fits \
                          gtpspec-out.fits \
                          gtptest-out.fits

include ${HD_STD_MAKEFILE}
