HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_PFILES       = gtexpcubesun.par \
						  gtexphpsun.par \
						  gtltcubesun.par \
						  gtsuntemp.par \
						  gtltsumsun.par 

include ${HD_STD_MAKEFILE}
