HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_XML_SUBDIR           = fermi/Likelihood

HD_TEST_XML             = A1_Functions.dtd \
                          A1_Functions.xml \
                          A1_Sources.dtd \
                          A1_Sources.xml \
                          A1_Srcs_noFuncLib.xml

include ${HD_STD_MAKEFILE}
