HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_LIBRARY_ROOT         = periodSearch

HD_LIBRARY_SRC_cxx      = ChiSquaredProb.cxx \
                          ChiSquaredTestArray.cxx \
                          FoldingAnalysis.cxx \
                          FourierAnalysis.cxx \
                          HTestArray.cxx \
                          PeriodicityTestApp.cxx \
                          PeriodSearchApp.cxx \
                          PeriodSearch.cxx \
                          PowerSpectrumApp.cxx \
                          StatisticViewer.cxx \
                          Z2nTestArray.cxx

HD_SUBDIRS              = gtpsearch gtpspec gtptest

HD_CXXFLAGS             = -fpermissive ${HD_STD_CXXFLAGS}

HD_INSTALL_LIBRARIES    = ${HD_LIBRARY_ROOT}

include ${HD_STD_MAKEFILE}
