HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_PFILES       = gtpsearch.par gtpspec.par gtptest.par

HD_TEST_PFILES          = test_periodSearch.par

include ${HD_STD_MAKEFILE}
