HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_REFDATA      = sources.xml \
                          ptsrcModel.xml \
                          srcModel.xml \
                          srcModel_egretdiffuse.xml \
                          srcModel_galprop.xml

HD_REFDATA_SUBDIR       = fermi/sane

include ${HD_STD_MAKEFILE}
