HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = fitsGen

HD_INSTALL_HEADERS      = EventClassifier.h \
			  FtFileBase.h \
                          Ft1File.h \
                          Ft2File.h \
                          MeritFile.h \
                          MeritFile2.h

include ${HD_STD_MAKEFILE}
