HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/DarkMatter/DS_DC2

HD_INSTALL_REFDATA      = lists.dat \
                          param.dat \
                          res100MeVBisBis.txt \
                          res10MeVBisBis.txt \
                          rndm00000060.dat \
                          rndm00000080.dat \
                          rndm00000100.dat \
                          rndm00000120.dat \
                          rndm00000140.dat \
                          rndm00000160.dat \
                          rndm00000180.dat

include ${HD_STD_MAKEFILE}
