HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = evtUtils

HD_INSTALL_HEADERS      = AliasDict.h \
                          EventCategory.h \
                          EventClass.h \
                          EventMap.h \
                          LinkDef.h

include ${HD_STD_MAKEFILE}
