HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_LIBRARY_ROOT         = orbitSim

HD_LIBRARY_SRC_cxx      = GLAST_slew_estimate.cxx \
                          OrbSim.cxx \
                          atFunctions.cxx \
                          functUtil.cxx \
                          read_ephem.cxx

HD_SUBDIRS              = orbSim

HD_CXXFLAGS             = ${HD_STD_CXXFLAGS}

HD_INSTALL_LIBRARIES    = ${HD_LIBRARY_ROOT}

include ${HD_STD_MAKEFILE}
