HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/map_tools/outref

HD_TEST_REFDATA         = testCube2.fits \
                          testCube.fits \
                          testCube_64bit.fits \
                          testCube2_64bit.fits

include ${HD_STD_MAKEFILE}
