HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_REFDATA      = LatBinnedTemplate \
                          LatCountCubeTemplate \
                          LatCountMapTemplate \
                          LatEnergyBinDef.tpl \
                          LatHealpixTemplate \
                          LatLightCurveTemplate \
                          LatSingleBinnedTemplate \
                          LatTimeBinDef.tpl

HD_REFDATA_SUBDIR       = fermi/evtbin

HD_TEST_REFDATA		= ft1tiny0.fits \
			  ft2filelist \
			  ft2tiny.fits \
			  ft2tiny2.fits \
                          energybins.fits \
                          ft1filelist \
                          ft1tiny.fits \
                          ft1tiny1.fits \
                          ft1tiny2.fits \
                          ft2tiny0.fits \
                          ft2tiny1.fits \
                          gbmtiny.fits

include ${HD_STD_MAKEFILE}
