HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/latResponse

HD_TEST_REFDATA		= aeff_epoch_0.fits \
					  aeff_epoch_1.fits \
					  edisp_epoch_0.fits \
					  edisp_epoch_1.fits \
					  psf_epoch_0.fits \
					  psf_epoch_1.fits \
					  psf_Pass5_v0_front.fits

include ${HD_STD_MAKEFILE}