HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = rspgen

HD_INSTALL_HEADERS      = CircularWindow.h \
                          CosineBinner.h \
                          GrbResponse.h \
			  IResponse.h \
                          IWindow.h \
                          PointResponse.h \
                          SpaceCraftCalculator.h

include ${HD_STD_MAKEFILE}
