HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_TEST_TASKS           = ST-unit-test \
                          ST-AGN-thread-test \
                          ST-pulsar-test \
                          ST-python-modules-test

HD_TEST_SUBDIRS         = data data/outref

include ${HD_STD_MAKEFILE}
