HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/rspgen/outref

HD_TEST_REFDATA		= PHA1.pha \
                          test_response1.rsp \
                          test_response2.rsp \
                          test_response3.rsp \
                          test_response4.rsp \
                          test_response5.rsp \
                          test_response6.rsp \
                          test_response7.rsp \
                          test_response8.rsp \
                          test_response_p7.rsp

include ${HD_STD_MAKEFILE}
