HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = xmlBase

HD_INSTALL_HEADERS      = Dom.h \
                          EResolver.h \
                          IFile.h \
                          XmlErrorHandler.h \
                          XmlParser.h

HD_SUBDIRS              = docMan

include ${HD_STD_MAKEFILE}
