HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/dataSubselector/outref

HD_TEST_REFDATA         = dss_test1.fits \
                          dss_test2.fits \
                          filtered_events_2.fits \
                          filtered_events.fits

include ${HD_STD_MAKEFILE}
