HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = st_facilities

HD_INSTALL_HEADERS      = Bilinear.h \
						  Env.h \
						  Environment.h \
                          FileSys.h \
                          FitsImage.h \
                          FitsTable.h \
                          FitsUtil.h \
                          GaussianQuadrature.h \
                          Util.h \
                          Timer.h \
                          dgaus8.h \
                          libStApiExports.h

include ${HD_STD_MAKEFILE}
