HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_PYTHON_LIBS  = BinnedLikelihood_test.py \
                          dataSubselector_tests.py \
                          default_tests.py \
                          evtbin_tests.py \
                          Likelihood_tests.py \
                          map_tools_tests.py \
                          obsSim_tests.py \
                          Pulsar_tests.py \
                          rspgen_tests.py \
                          setPaths.py

include ${HD_STD_MAKEFILE}
