HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_LIBRARY_ROOT         = st_app

HD_LIBRARY_SRC_cxx      = AppParGroup.cxx \
                          StApp.cxx \
                          StAppFactory.cxx \
                          StAppGui.cxx \
                          ballistic_main.cxx

HD_CXXFLAGS             = ${PYTHON_INC} ${HD_STD_CXXFLAGS}

HD_INSTALL_LIBRARIES    = ${HD_LIBRARY_ROOT}

include ${HD_STD_MAKEFILE}
