HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_SHELL_SCRIPTS = modeleditor

HD_INSTALL_PYTHON_LIBS  = AddCatalogSourcesDialog.py \
						  CatalogSourceExtractor.py \
						  DS9Connector.py \
						  ElementEditor.py \
                          Element.py \
                          FitsFile.py \
                          HelpWindow.py \
                          ModelEditor.py \
                          ParameterEditor.py \
                          Parameter.py \
                          ParameterSet.py \
                          SourceEditor.py \
                          SourceLibraryDocumentEditor.py \
                          SourceLibraryDocument.py \
                          SourceLibraryEditor.py \
                          SourceLibrary.py \
                          Source.py \
                          SpatialModelEditor.py \
                          SpatialModel.py \
                          SpectrumEditor.py \
                          Spectrum.py

HD_INSTALL_HELP         = help.txt \
						  modeleditor.txt

include ${HD_STD_MAKEFILE}
