HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = astro

HD_INSTALL_HEADERS      = EarthCoordinate.h \
                          EarthOrbit.h \
                          GPS.h \
                          HTM.h \
                          IGRField.h \
                          IGRF_data.h \
                          JulianDate.h \
                          LatProperties.h \
                          Photon.h \
                          PointingHistory.h \
                          PointingInfo.h \
                          PointingTransform.h \
                          Quaternion.h \
                          SkyDir.h \
                          SkyFunction.h \
                          SkyProj.h \
                          SkyStat.h \
                          SolarSystem.h

include ${HD_STD_MAKEFILE}
