HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = orbitSim

HD_INSTALL_HEADERS      = DynamicStruct.h \
                          GLAST_slew_estimate.h \
                          OrbSim.h \
                          atFunctions.h \
                          functions.h \
                          orbitSimStruct.h \
                          read_ephem.h

include ${HD_STD_MAKEFILE}
