HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/test-scripts

HD_TEST_REFDATA         = _3c84-obssim.xml \
                          _3c84-srcmdl.xml \
                          _3c84_sim_scData_0000.fits \
                          source-names.txt \
                          groD4-dc2v5.fits \
                          my_pulsar_events_v3.fits \
                          master_pulsardb_v2.fits \
                          my_pulsar_spacecraft_data_v3r1.fits \
                          my_pulsar_events_phase_v3r1.fits \
                          3C84-FT1.fits \
                          3C84-P7REP-FT1.fits \
                          3C84-FT2.fits \
                          3C84-model.xml \

include ${HD_STD_MAKEFILE}
