HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_REFDATA      = PulsarDb.tpl

HD_REFDATA_SUBDIR       = fermi/pulsarDb

HD_TEST_REFDATA         = PulsarDb.tpl \
                          PulsarDb.tpl \
                          PulsarDb_orbital_bt.tpl \
                          PulsarDb_orbital_dd.tpl \
                          PulsarDb_orbital_ell1.tpl \
                          PulsarDb_orbital_mss.tpl \
                          PulsarDb_primary.tpl \
                          PulsarDb_spin_freq.tpl \
                          PulsarDb_spin_hp.tpl \
                          PulsarDb_spin_per.tpl \
                          baddb_badparenthesis1.txt \
                          baddb_badparenthesis2.txt \
                          baddb_badparenthesis3.txt \
                          baddb_badparenthesis4.txt \
                          baddb_badparenthesis5.txt \
                          baddb_badparenthesis6.txt \
                          baddb_badparenthesis7.txt \
                          baddb_badparenthesis8.txt \
                          baddb_escapedquote.txt \
                          baddb_nestedvector.txt \
                          baddb_noextname.txt \
                          baddb_noheader.txt \
                          baddb_nosuchephstyle.txt \
                          baddb_nosuchextname.txt \
                          baddb_nosuchfield.txt \
                          baddb_quotedvector.txt \
                          baddb_toolittlefield.txt \
                          baddb_toomanyfield.txt \
                          baddb_unbalancedquote.txt \
                          baddb_vectoredscalar.txt \
                          column_samples.fits \
                          groD4-dc2v3.fits \
                          groD4-dc2v4.fits \
                          groD4-dc2v4r1.fits \
                          groD4-dc2v4r2.fits \
                          groD4-dc2v5.fits \
                          groD4-dc2v6.fits \
                          gtephem_glitch.txt \
                          gtephem_leapsec.fits \
                          gtephem_remark.txt \
                          master_pulsardb_v2.fits \
                          okdb_emptyfield.txt \
                          okdb_extraescape.txt \
                          okdb_extraquote.txt \
                          okdb_extraspace.txt \
                          okdb_notallcolumn1.txt \
                          okdb_notallcolumn2.txt \
                          psrdb_binary.txt \
                          psrdb_binary_bt.txt \
                          psrdb_name.txt \
                          psrdb_obs.txt \
                          psrdb_remark.txt \
                          psrdb_spin.txt \
                          psrdb_spin_fermi.txt \
                          psrdb_spin_hp.txt \
                          psrdb_spin_per.txt \
                          psrdb_user.fits \
                          test_FrequencyEph.tpl \
                          test_PeriodEph.tpl \
                          test_SimpleDdEph.tpl \
                          test_TextPulsarDb.tpl \
                          test_pulsarDb.tpl \
                          test_pulsarDb_badorbital.tpl \
                          test_pulsarDb_badspin.tpl \
                          test_pulsarDb_g0g1g2g1.tpl \
                          test_pulsarDb_g2g1g0g1.tpl \
                          test_pulsarDb_g2g1g2g0.tpl \
                          testpsrdb_crab.fits \
                          testpsrdb_dbmanip.fits \
                          testpsrdb_dbmanip_fermi.fits \
                          testpsrdb_ephcomp.fits \
                          testpsrdb_text.fits \
                          timeformat_glast.tpl \
                          wrongdb_binary.txt \
                          wrongdb_spin.txt \

include ${HD_STD_MAKEFILE}
