HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_PFILES       = gtbkg.par \
                          gtdiffrsp.par \
                          gtexpcube2.par \
                          gtexpmap.par \
                          gtfindsrc.par \
                          gtlike.par \
                          gtltcube.par \
                          gtltsum.par \
                          gtmodel.par \
                          gtpsf.par \
                          gtsrcmaps.par \
                          gtsrcprob.par \
                          gttsmap.par

include ${HD_STD_MAKEFILE}
