HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_REFDATA      = edisp_P6_v11_diff_back.fits \
                          edisp_P6_v11_diff_front.fits \
                          edisp_P6_v1_diff_back.fits \
                          edisp_P6_v1_diff_front.fits \
                          edisp_P6_v1_source_back.fits \
                          edisp_P6_v1_source_front.fits \
                          edisp_P6_v1_trans_back.fits \
                          edisp_P6_v1_trans_front.fits \
                          edisp_P6_v3_diff_back.fits \
                          edisp_P6_v3_diff_front.fits \
                          edisp_P6_v3_source_back.fits \
                          edisp_P6_v3_source_front.fits \
                          edisp_P6_v3_trans_back.fits \
                          edisp_P6_v3_trans_front.fits \
                          edisp_P7CLEAN_V6_back.fits \
                          edisp_P7CLEAN_V6_front.fits \
                          edisp_P7SOURCE_V6MC_back.fits \
                          edisp_P7SOURCE_V6MC_front.fits \
                          edisp_P7SOURCE_V6_back.fits \
                          edisp_P7SOURCE_V6_front.fits \
                          edisp_P7TRANSIENT_V6_back.fits \
                          edisp_P7TRANSIENT_V6_front.fits \
                          edisp_P7ULTRACLEAN_V6_back.fits \
                          edisp_P7ULTRACLEAN_V6_front.fits \
                          edisp_P7REP_CLEAN_V10_back.fits \
			  			  edisp_P7REP_CLEAN_V10_front.fits \
                          edisp_P7REP_SOURCE_V10_back.fits \
                          edisp_P7REP_SOURCE_V10_front.fits \
                          edisp_P7REP_TRANSIENT_V10_back.fits \
                          edisp_P7REP_TRANSIENT_V10_front.fits \
                          edisp_P7REP_ULTRACLEAN_V10_back.fits \
                          edisp_P7REP_ULTRACLEAN_V10_front.fits \
                          edisp_P7REP_CLEAN_V15_back.fits \
			  			  edisp_P7REP_CLEAN_V15_front.fits \
                          edisp_P7REP_SOURCE_V15_back.fits \
                          edisp_P7REP_SOURCE_V15_front.fits \
                          edisp_P7REP_TRANSIENT_V15_back.fits \
                          edisp_P7REP_TRANSIENT_V15_front.fits \
                          edisp_P7REP_ULTRACLEAN_V15_back.fits \
                          edisp_P7REP_ULTRACLEAN_V15_front.fits \
                          edisp_p6_v3_dataclean_back.fits \
                          edisp_p6_v3_dataclean_front.fits \
                          edisp_P8R2_CLEAN_V6_EDISP.fits \
						  edisp_P8R2_CLEAN_V6_FB.fits \
						  edisp_P8R2_CLEAN_V6_PSF.fits \
						  edisp_P8R2_SOURCE_V6_EDISP.fits \
						  edisp_P8R2_SOURCE_V6_FB.fits \
						  edisp_P8R2_SOURCE_V6_PSF.fits \
						  edisp_P8R2_TRANSIENT010E_V6_EDISP.fits \
						  edisp_P8R2_TRANSIENT010E_V6_FB.fits \
						  edisp_P8R2_TRANSIENT010E_V6_PSF.fits \
						  edisp_P8R2_TRANSIENT010_V6_EDISP.fits \
						  edisp_P8R2_TRANSIENT010_V6_FB.fits \
						  edisp_P8R2_TRANSIENT010_V6_PSF.fits \
						  edisp_P8R2_TRANSIENT015S_V6_EDISP.fits \
						  edisp_P8R2_TRANSIENT015S_V6_FB.fits \
						  edisp_P8R2_TRANSIENT015S_V6_PSF.fits \
						  edisp_P8R2_TRANSIENT020E_V6_EDISP.fits \
						  edisp_P8R2_TRANSIENT020E_V6_FB.fits \
						  edisp_P8R2_TRANSIENT020E_V6_PSF.fits \
						  edisp_P8R2_TRANSIENT020_V6_EDISP.fits \
						  edisp_P8R2_TRANSIENT020_V6_FB.fits \
						  edisp_P8R2_TRANSIENT020_V6_PSF.fits \
						  edisp_P8R2_TRANSIENT100E_V6_EDISP.fits \
						  edisp_P8R2_TRANSIENT100E_V6_FB.fits \
						  edisp_P8R2_TRANSIENT100E_V6_PSF.fits \
						  edisp_P8R2_TRANSIENT100S_V6_EDISP.fits \
						  edisp_P8R2_TRANSIENT100S_V6_FB.fits \
						  edisp_P8R2_TRANSIENT100S_V6_PSF.fits \
						  edisp_P8R2_TRANSIENT100_V6_EDISP.fits \
						  edisp_P8R2_TRANSIENT100_V6_FB.fits \
						  edisp_P8R2_TRANSIENT100_V6_PSF.fits \
						  edisp_P8R2_ULTRACLEAN_V6_EDISP.fits \
						  edisp_P8R2_ULTRACLEAN_V6_FB.fits \
						  edisp_P8R2_ULTRACLEAN_V6_PSF.fits \
						  edisp_P8R2_ULTRACLEANVETO_V6_EDISP.fits \
						  edisp_P8R2_ULTRACLEANVETO_V6_FB.fits \
						  edisp_P8R2_ULTRACLEANVETO_V6_PSF.fits
                          

HD_REFDATA_SUBDIR       = fermi/caldb/CALDB/data/glast/lat/bcf/edisp

include ${HD_STD_MAKEFILE}
