HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_LIBRARY_ROOT         = dataSubselector

HD_LIBRARY_SRC_cxx      = BitMaskCut.cxx \
                          CutBase.cxx \
                          Cuts.cxx \
                          Gti.cxx \
                          GtiCut.cxx \
                          RangeCut.cxx \
                          SkyConeCut.cxx \
                          VersionCut.cxx

HD_CXXFLAGS             = ${HD_STD_CXXFLAGS}

HD_INSTALL_LIBRARIES    = ${HD_LIBRARY_ROOT}

HD_SUBDIRS              = dataSubselector gtmaketime viewCuts

include ${HD_STD_MAKEFILE}
