HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       = 

HD_TEST_REFDATA         = BGO_energy_grid.dat \
                          GRBTMP000000.dat \
                          NaI_energy_grid.dat \
                          Thermal_LAT_A_025.dat \
                          Thermal_LAT_A_073.dat \
                          Thermal_LAT_A_617.dat \
                          Thermal_LAT_C_014.dat \
                          pulse_002.dat \
                          test.dat

HD_REFDATA_SUBDIR       = fermi/GRBtemplate

include ${HD_STD_MAKEFILE}
