HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/astro

HD_TEST_REFDATA         = test_FT2.fits \
						  history_test.txt \
						  dgrf1945.dat \
						  dgrf1950.dat \
						  dgrf1955.dat \
						  dgrf1960.dat \
						  dgrf1965.dat \
						  dgrf1970.dat \
						  dgrf1975.dat \
						  dgrf1980.dat \
						  dgrf1985.dat \
						  dgrf1990.dat \
						  dgrf1995.dat \
						  dgrf2000.dat \
						  dgrf2005.dat \
						  dgrf2010.dat \
						  igrf1900.dat \
						  igrf1905.dat \
						  igrf1910.dat \
						  igrf1915.dat \
						  igrf1920.dat \
						  igrf1925.dat \
						  igrf1930.dat \
						  igrf1935.dat \
						  igrf1940.dat \
						  igrf2005.dat \
						  igrf2010.dat \
						  igrf2010s.dat \
						  igrf2015.dat \
						  igrf2015s.dat

include ${HD_STD_MAKEFILE}
