HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_SUBDIRS              = observationSim src pfiles xml

HD_TEST_SUBDIRS         = src/test data xml data/outref

include ${HD_STD_MAKEFILE}
