HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_LIBRARY_ROOT         = SolarSystemTools

HD_LIBRARY_SRC_cxx      = BinnedExposureSun.cxx \
						  CosineBinner2D.cxx \
						  ExposureCubeSun.cxx \
						  ExposureSun.cxx \
						  FitsSolarProfile.cxx \
						  HealpixExposureSun.cxx \
						  LikeExposureSun.cxx \
						  SolarProfile.cxx \
						  SolarTemplate.cxx 

HD_SUBDIRS              = gtexphpsun \
						  gtltsumsun \
						  gtsuntemp \
						  makeSolarExposureCube \
						  #gtexpcubesun 

HD_CXXFLAGS             = ${HD_STD_CXXFLAGS}

HD_INSTALL_LIBRARIES    = ${HD_LIBRARY_ROOT}

include ${HD_STD_MAKEFILE}
