HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_LIBRARY_ROOT         = catalogAccess

HD_LIBRARY_SRC_cxx      = catalog_sel.cxx \
                          catalog.cxx \
                          catalog_io.cxx \
                          catalog_ioText.cxx \
                          quantity.cxx

HD_CXXFLAGS             = ${HD_STD_CXXFLAGS}

HD_INSTALL_LIBRARIES    = ${HD_LIBRARY_ROOT}

include ${HD_STD_MAKEFILE}
