HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_REFDATA      = LatResponseTemplate

HD_REFDATA_SUBDIR       = fermi/rspgen

HD_TEST_REFDATA         = rspgen_energy_bins.fits PHA1.pha ft2tiny.fits

include ${HD_STD_MAKEFILE}
