HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_PYTHON_LIBS  = AnalysisBase.py \
                          BinnedAnalysis.py \
                          CompositeLikelihood.py \
                          Composite2.py \
                          FluxDensity.py \
                          HippoPlot.py \
                          IntegralUpperLimit.py \
                          LikelihoodState.py \
                          MPLPlot.py \
                          RootPlot.py \
                          SED.py \
                          SimpleDialog.py \
                          SrcAnalysis.py \
                          SrcModel.py \
                          SummedLikelihood.py \
                          UnbinnedAnalysis.py \
                          UpperLimits.py \
                          package_paths.py \
                          test_model.py

include ${HD_STD_MAKEFILE}
