HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_LIBRARY_ROOT         = pulsarDb

HD_LIBRARY_SRC_cxx      = BtModelEph.cxx \
                          Ell1ModelEph.cxx \
                          EphChooser.cxx \
                          EphComputer.cxx \
                          EphComputerApp.cxx \
                          EphStatus.cxx \
                          FrequencyEph.cxx \
                          HighPrecisionEph.cxx \
                          MssModelEph.cxx \
                          OrbitalEph.cxx \
                          PdotCanceler.cxx \
                          PeriodEph.cxx \
                          PulsarDb.cxx \
                          PulsarDbApp.cxx \
                          PulsarEph.cxx \
                          PulsarToolApp.cxx \
                          SimpleDdEph.cxx

HD_SUBDIRS              = gtephem gtpulsardb

HD_CXXFLAGS             = ${HD_STD_CXXFLAGS}

HD_INSTALL_LIBRARIES    = ${HD_LIBRARY_ROOT}

include ${HD_STD_MAKEFILE}
