HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = observationSim

HD_INSTALL_HEADERS      = ContainerBase.h \
                          Event.h \
                          EventContainer.h \
                          ScData.h \
                          ScDataContainer.h \
                          Simulator.h \
                          Spacecraft.h

include ${HD_STD_MAKEFILE}
