HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_LIBRARY_ROOT         = rootIrfLoader

HD_LIBRARY_SRC_cxx      = Aeff.cxx \
                          Edisp.cxx \
                          IrfBase.cxx \
                          Psf.cxx \
                          SkyDir.cxx

HD_CXXFLAGS             = ${HD_STD_CXXFLAGS}

HD_INSTALL_HEADERS      = Aeff.h \
                          IrfBase.h \
                          Psf.h

HD_INSTALL_LIBRARIES    = ${HD_LIBRARY_ROOT}

include ${HD_STD_MAKEFILE}
