HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/optimizers/outref

HD_TEST_REFDATA         = Mc.fits \
                          outputModels.xml

include ${HD_STD_MAKEFILE}
