HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_LIBRARY_ROOT         = observationSim

HD_LIBRARY_SRC_cxx      = ContainerBase.cxx \
                          EgretSc.cxx \
                          EventContainer.cxx \
                          LatSc.cxx \
                          ScDataContainer.cxx \
                          Simulator.cxx

HD_SUBDIRS              = obsSim

HD_CXXFLAGS             = ${HD_STD_CXXFLAGS}

HD_INSTALL_LIBRARIES    = ${HD_LIBRARY_ROOT}

include ${HD_STD_MAKEFILE}
