HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/GRBobs/outref

HD_TEST_REFDATA         = BGO_GRBOBS_010101011.lc \
                          BGO_GRBOBS_010101519.lc \
                          BGO_GRBOBS_010103456.lc \
                          BGO_GRBOBS_010103472.lc \
                          GRBOBS_010101011.DEF \
                          GRBOBS_010101011_PAR.txt \
                          GRBOBS_010101519.DEF \
                          GRBOBS_010101519_PAR.txt \
                          GRBOBS_010103456.DEF \
                          GRBOBS_010103456_PAR.txt \
                          GRBOBS_010103472.DEF \
                          GRBOBS_010103472_PAR.txt \
                          NaI_GRBOBS_010101011.lc \
                          NaI_GRBOBS_010101519.lc \
                          NaI_GRBOBS_010103456.lc \
                          NaI_GRBOBS_010103472.lc \
                          test_GRB.out

include ${HD_STD_MAKEFILE}
