HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = genericSources

HD_INSTALL_HEADERS      = FileSpectrum.h \
                          FileSpectrumMap.h \
                          FitsTransient.h \
                          GaussianSource.h \
                          GaussianSpectrum.h \
                          Isotropic.h \
                          IsotropicFileSpectrum.h \
                          MapCube.h \
                          MapSource.h \
                          PeriodicSource.h \
                          Pulsar.h \
                          RadialSource.h \
                          SimpleTransient.h \
                          SourcePopulation.h \
                          SpectralTransient.h \
                          TF1Map.h \
                          TF1Spectrum.h \
                          TransientTemplate.h

include ${HD_STD_MAKEFILE}
