HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = flux

HD_INSTALL_HEADERS      = AGNSpectrum.h \
                          CompositeSource.h \
                          EventSource.h \
                          Flux.h \
                          FluxException.h \
                          FluxMgr.h \
                          FluxSource.h \
                          IFlux.h \
                          ISpectrum.h \
                          ISpectrumFactory.h \
                          LaunchDirection.h \
                          LaunchPoint.h \
                          MapSpectrum.h \
                          rootplot.h \
                          SimpleSpectrum.h \
                          Spectrum.h \
                          SpectrumFactory.h \
                          SpectrumFactoryTable.h

include ${HD_STD_MAKEFILE}
