HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_REFDATA      = LatCountsMapTemplate \
                          LivetimeCubeTemplate \
                          TsMapTemplate \
                          mapcube.fits

HD_REFDATA_SUBDIR       = fermi/Likelihood

HD_TEST_REFDATA		= Crab_model.xml \
                          anticenter_expMap.fits \
                          anticenter_model.xml \
                          anticenter_model_2.xml \
                          anticenter_model_3.xml \
                          anticenter_model_4.xml \
                          cena_lobes_parkes_south.fits \
                          expMap_0.fits \
                          expMap_1.fits \
                          expMap_2.fits \
                          expMap_3.fits \
                          expMap_4.fits \
                          galdiffuse_events_0000.fits \
                          gammac_dif.dat \
                          oneday_scData_0000.fits \
                          single_src_events_0000.fits

include ${HD_STD_MAKEFILE}
