HD_COMPONENT_NAME	= glast

HD_COMPONENT_VERS	= 

HD_INC_SUBDIR           = src/base

HD_INSTALL_HEADERS      = alm.h \
                          alm_map_tools.h \
                          alm_filter_tools.h \
                          arr.h \
                          constants.h \
                          cxxutils.h \
                          healpix_base.h \
                          healpix_map.h \
                          message_error.h \
                          pointing.h \
                          powspec.h \
                          vec3.h \
                          xcomplex.h

include ${HD_STD_MAKEFILE}
