HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = pulsarDb

HD_INSTALL_HEADERS      = BtModelEph.h \
                          Ell1ModelEph.h \
                          EphChooser.h \
                          EphComputer.h \
                          EphComputerApp.h \
                          EphStatus.h \
                          FormattedEph.h \
                          FrequencyEph.h \
                          HighPrecisionEph.h \
                          MssModelEph.h \
                          OrbitalEph.h \
                          PdotCanceler.h \
                          PeriodEph.h \
                          PulsarDb.h \
                          PulsarDbApp.h \
                          PulsarEph.h \
                          PulsarToolApp.h \
                          SimpleDdEph.h \
                          TextPulsarDb.h

include ${HD_STD_MAKEFILE}
