HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/tip/outref

HD_TEST_REFDATA         = a1-copy.pha \
                          aeff_DC1-copy.fits \
                          created_image.fits \
                          created_table.fits \
                          ft1_kwtest.fits \
                          IFileSvc_error.fits \
                          IFileSvc_no_template.fits \
                          IFileSvc_success.fits \
                          new_ft1.fits \
                          new_groD4-dc2v1.fits \
                          new_image2.fits \
                          new_image3.fits \
                          new_image4.fits \
                          new_image.fits \
                          testFitsColumnByMH.fits \
                          tipfile-copy.fits \
                          tipfile.fits \
                          unsigned_int.fits

include ${HD_STD_MAKEFILE}
