HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = healpix/base

HD_INSTALL_HEADERS      = alm.h \
                          alm_filter_tools.h \
                          alm_map_tools.h \
                          alm_powspec_tools.h \
                          arr.h \
                          bluestein.h \
                          constants.h \
                          cxxutils.h \
                          datatypes.h \
                          fftpack.h \
                          fftpack_support.h \
                          fitshandle.h \
                          healpix_base.h \
                          healpix_map.h \
                          healpix_map_fitsio.h \
                          longnam.h \
                          ls_fft.h \
                          message_error.h \
                          openmp_support.h \
                          planck_rng.h \
                          pointing.h \
                          powspec.h \
                          rotmatrix.h \
                          vec3.h \
                          xcomplex.h \
                          ylmgen.h

include ${HD_STD_MAKEFILE}
