HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_LIBRARY_ROOT         = rspgen

HD_LIBRARY_SRC_cxx      = CircularWindow.cxx \
                          CosineBinner.cxx \
                          GrbResponse.cxx \
                          IResponse.cxx \
                          PointResponse.cxx \
                          RspGenApp.cxx \
                          SpaceCraftCalculator.cxx

HD_SUBDIRS              = gtrspgen

HD_CXXFLAGS             = ${HD_STD_CXXFLAGS}

HD_INSTALL_LIBRARIES    = ${HD_LIBRARY_ROOT}

include ${HD_STD_MAKEFILE}
