HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = st_graph

HD_INSTALL_HEADERS      = Axis.h \
                          Engine.h \
                          IEventReceiver.h \
                          IFrame.h \
                          IPlot.h \
                          ITabFolder.h \
                          LinkDef.h \
                          Placer.h \
                          RootFrame.h \
                          Sequence.h \
                          StGui.h \
                          MPLFrame.h

include ${HD_STD_MAKEFILE}
