HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/Likelihood/outref

HD_TEST_REFDATA         = binnedExposure.fits \
                          cntsMap.fits \
                          countsMap.fits \
                          dataMap.fits \
                          modelMap.fits \
                          srcMaps.fits

include ${HD_STD_MAKEFILE}
