HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = irfInterface

HD_INSTALL_HEADERS      = AcceptanceCone.h \
                          EfficiencyFactor.h \
                          IAeff.h \
                          IEdisp.h \
                          IEfficiencyFactor.h \
                          IPsf.h \
                          IrfLoader.h \
                          IrfRegistry.h \
                          Irfs.h \
                          IrfsFactory.h

include ${HD_STD_MAKEFILE}
