HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_TEST_TASKS           = test_timeSystem

HD_TEST_CXXTASK         = ${HD_TEST_TASKS}

HD_TEST_CXXTASK_SRC_cxx	= test_timeSystem.cxx

HD_CXXFLAGS             = ${HD_STD_CXXFLAGS} -I../..

HD_CXXLIBS              = ${HD_LFLAGS} \
                          ${GT_TIMESYSTEM_LIBS} \
                          ${GT_STD_CXXLIBS}

include ${HD_STD_MAKEFILE}
