HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INC_SUBDIR           = map_tools

HD_INSTALL_HEADERS      = DiffuseFunction.h \
                          Exposure.h \
                          MapParameters.h \
                          Parameters.h \
                          SkyImage.h

include ${HD_STD_MAKEFILE}
