HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/tip

HD_TEST_REFDATA         = a1.pha \
                          aeff_DC1.fits \
                          arlac.pha \
                          ft1.tpl \
			  large_file.tpl \
                          FT2.root \
                          groD4-dc2v1.fits \
                          merit.root

include ${HD_STD_MAKEFILE}
