HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_REFDATA_SUBDIR       = fermi/observationSim/outref

HD_TEST_REFDATA         = test_events_0000.fits \
                          test_scData_0000.fits

include ${HD_STD_MAKEFILE}
