HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_LIBRARY_ROOT         = map_tools

HD_LIBRARY_SRC_cxx      = DiffuseFunction.cxx \
                          Exposure.cxx \
                          MapParameters.cxx \
                          Parameters.cxx \
                          SkyImage.cxx

HD_CXXFLAGS             = ${HD_STD_CXXFLAGS} -fpermissive

HD_INSTALL_LIBRARIES    = ${HD_LIBRARY_ROOT}

HD_SUBDIRS              = cube_display exposure_map

include ${HD_STD_MAKEFILE}
